arena:
  pos1:
    world: world
    x: 0.0
    y: 64.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
  pos2:
    world: world
    x: 5.0
    y: 64.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
  lobby:
    world: world
    x: 0.0
    y: 64.0
    z: 10.0
    yaw: 0.0
    pitch: 0.0

kit:
  items:
    - DIAMOND_SWORD
    - BOW
    - ARROW:32
  armor:
    - DIAMOND_HELMET
    - DIAMOND_CHESTPLATE
    - DIAMOND_LEGGINGS
    - DIAMOND_BOOTS

challenge-timeout: 60
