name: Duel1v1
version: 1.0.1
main: me.hendi.duel1v1.Duel1v1
api-version: '1.21'
author: Hendi
description: Plugin simples para duelos 1v1
softdepend: [WorldGuard, ClearLag, ClearLagg, ClearLaggEnhanced]

commands:
  duelo:
    description: Gerencia duelos 1v1
    usage: /<command> <jogador> | aceitar <jogador> | recusar <jogador> | sair | cancelar
    aliases: [duel]
  duelonpc:
    description: Gerencia o NPC clicável da fila de duelos
    usage: /<command> [remover]
    permission: duel.admin

permissions:
  duel.use:
    description: Permite usar comandos de duelo
    default: true
  duel.admin:
    description: Permite gerenciar arenas
    default: op
